apiVersion: v1
kind: ConfigMap
metadata:
  name: php-config
  labels:
    tier: backend
data:
  php-fpm.conf  : |
    ;;;;;;;;;;;;;;;;;;;;;
    ; FPM Configuration without comments
    ; based on https://github.com/oprudkyi/openshift-templates/blob/master/php-fpm/php-fpm.yaml
    [global]
    include=/usr/local/etc/php-fpm.d/*.conf
  www.conf : |
    [www]
    user = www-data
    group = www-data
    listen = 127.0.0.1:9000
    pm = dynamic
    pm.max_children = 5
    pm.start_servers = 2
    pm.min_spare_servers = 1
    pm.max_spare_servers = 3
  docker.conf : | 
    [global]
    error_log = /tmp/php-fpm-error.log
    [www]
    access.log = /tmp/php-fpm-access.log
    access.format = "%R - %u %t \"%m %r\" %s" 
    clear_env = no
    catch_workers_output = yes
  zz-docker.conf : | 
    [global]
    daemonize = no
    [www]
    listen = [::]:9000